### ISSUE TITLE
Unicode error on Windows

### ISSUE THREAD

**Issue by wenkokke** [wenkokke/talondoc#95]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\a\talondoc\talondoc\.tox\py311\Scripts\talondoc.exe\__main__.py", line 7, in <module>
  File "D:\a\talondoc\talondoc\.tox\py311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\talondoc\talondoc\.tox\py311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\a\talondoc\talondoc\.tox\py311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\talondoc\talondoc\.tox\py311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\talondoc\talondoc\.tox\py311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\talondoc\talondoc\.tox\py311\Lib\site-packages\talondoc\__init__.py", line 103, in autogen
    generate(
  File "D:\a\talondoc\talondoc\.tox\py311\Lib\site-packages\talondoc\autosummary\generate.py", line 85, in generate
    package_entry = analyse_package(
                    ^^^^^^^^^^^^^^^^
  File "D:\a\talondoc\talondoc\.tox\py311\Lib\site-packages\talondoc\analyze\__init__.py", line 74, in analyse_package
    analyse_python_file(registry, file_path, package_entry)
  File "D:\a\talondoc\talondoc\.tox\py311\Lib\site-packages\talondoc\analyze\__init__.py", line 144, in analyse_python_file
    importlib.import_module(name=module_name, package=package.name)
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\a\talondoc\talondoc\.tox\py311\tmp\knausj_talon\tags\emoji\emoji.py", line 27, in <module>
    k.strip(): v.strip() for k, v in [line.split(",", 1) for line in f]
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\talondoc\talondoc\.tox\py311\tmp\knausj_talon\tags\emoji\emoji.py", line 27, in <listcomp>
    k.strip(): v.strip() for k, v in [line.split(",", 1) for line in f]
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 62: character maps to <undefined>
```

**Comment by wenkokke** [comment]
See, e.g., [this run](https://github.com/wenkokke/talondoc/actions/runs/4457513644/jobs/7828643857).

**Comment by wenkokke** [comment]
This is actually an error in `knausj_talon` which never shows up because Talon's Python always runs in UTF8 mode.

When running talondoc on Windows, make sure to set the `PYTHONUTF8` environment variable to `1`.
